import React from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

import Logo from "../assets/Logo.svg";
import HomeIcon from "../assets/Home.svg";
import PortfolioIcon from "../assets/Portfolio.svg";
import SearchIcon from "../assets/SearchIcon.svg";
import SunIcon from "../assets/SunIcon.svg";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="gap-[20px] flex">
          <div className="flex">
            <Logo />
            <h2>Logoipsm</h2>
          </div>
          <div className="flex">
            <HomeIcon />
            <Link href="/">Home</Link>
          </div>
          <div className="flex">
            <PortfolioIcon />
            <Link href="/portfolio">Portfolio</Link>
          </div>
          <div className="flex">
            <div className="flex">
              <SearchIcon />
              <input
                className="bg-white text-black"
                placeholder="Search"
              ></input>
            </div>
            <button>
              <SunIcon />
            </button>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
