import React from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import tw from "tailwind-styled-components";

import Logo from "../assets/Logo.svg";
import HomeIcon from "../assets/Home.svg";
import PortfolioIcon from "../assets/Portfolio.svg";
import SearchIcon from "../assets/SearchIcon.svg";
import SunIcon from "../assets/SunIcon.svg";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const NavbarContainer = tw.div`
  gap-[20px]
  flex content-center
  justify-between
  bg-[#13121A]
  p-[20px]
  w-[100vw]
`;

const NavbarSearchContainer = tw.div`
  flex
  gap-[10px]
  relative
`;

const NavbarSearchInput = tw.input`
  bg-[#191925]
  text-white
  p-[5px]
  rounded-sm
  pl-[30px]
`;

const NavbarThemeButton = tw.button`
  bg-[#191925]
  p-[5px]
  rounded-md
`;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavbarContainer>
          <div className="flex gap-[10px]">
            <Logo />
            <h2>Logoipsm</h2>
          </div>
          <div className="flex gap-[20px]">
            <div className="flex gap-[10px]">
              <HomeIcon />
              <Link href="/">Home</Link>
            </div>
            <div className="flex gap-[10px]">
              <PortfolioIcon />
              <Link href="/portfolio">Portfolio</Link>
            </div>
          </div>
          <div className="flex gap-[20px]">
            <NavbarSearchContainer>
              <SearchIcon className="absolute top-[10px] left-[5px]" />
              <NavbarSearchInput placeholder="Search" />
            </NavbarSearchContainer>
            <NavbarThemeButton>
              <SunIcon />
            </NavbarThemeButton>
          </div>
        </NavbarContainer>
        {children}
      </body>
    </html>
  );
}
